import { useEffect, useState } from 'react'
import { Alert, Button, Card, Col, Form, Row, Spinner } from 'react-bootstrap'
import { quizApi } from '../api/quizApi.js'
import PageHeader from '../components/PageHeader.jsx'

const emptyQuestion=()=>({text:'',explanation:'',order:1,answerOptions:[{text:'',isCorrect:true},{text:'',isCorrect:false},{text:'',isCorrect:false},{text:'',isCorrect:false}]})
const initial={title:'',description:'',topic:'Software Testing',isPublished:false,startingHp:100,mistakeDamage:20,bossFightEnabled:false,bossName:'Regression Dragon',bossHp:300,bossDamagePerStreak:100,questions:[emptyQuestion()]}

// QuizEditorPage depends on QuizInput in the backend. Keep field names aligned with QuizDtos.cs.
export default function QuizEditorPage({ quizId, go }) {
  const [quiz,setQuiz]=useState(initial); const [loading,setLoading]=useState(Boolean(quizId)); const [saving,setSaving]=useState(false); const [error,setError]=useState('')
  useEffect(()=>{if(quizId)quizApi.get(quizId).then(setQuiz).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[quizId])
  const field=(name,value)=>setQuiz(q=>({...q,[name]:value}))
  const qField=(index,name,value)=>setQuiz(q=>({...q,questions:q.questions.map((item,i)=>i===index?{...item,[name]:value}:item)}))
  const optionField=(qi,oi,name,value)=>setQuiz(q=>({...q,questions:q.questions.map((item,i)=>i===qi?{...item,answerOptions:item.answerOptions.map((o,j)=>j===oi?{...o,[name]:value}:name==='isCorrect'?{...o,isCorrect:false}:o)}:item)}))
  const submit=async event=>{event.preventDefault();setSaving(true);setError('');try{quizId?await quizApi.update(quizId,quiz):await quizApi.create(quiz);go('mine')}catch(e){setError(e.message)}finally{setSaving(false)}}
  if(loading)return <Spinner animation="border"/>
  return <><PageHeader eyebrow="QUIZBYGGER" title={quizId?'Rediger quiz':'Lag ny quiz'}/>{error&&<Alert variant="danger">{error}</Alert>}<Form onSubmit={submit}>
    <Card className="editor-card mb-3"><Card.Body><h3>1. Grunninformasjon</h3><Row className="g-3"><Col md={8}><Form.Label>Tittel</Form.Label><Form.Control required value={quiz.title} onChange={e=>field('title',e.target.value)}/></Col><Col md={4}><Form.Label>Tema</Form.Label><Form.Control required value={quiz.topic} onChange={e=>field('topic',e.target.value)}/></Col><Col xs={12}><Form.Label>Beskrivelse</Form.Label><Form.Control as="textarea" rows={2} required value={quiz.description} onChange={e=>field('description',e.target.value)}/></Col><Col md={4}><Form.Label>Start-HP</Form.Label><Form.Control type="number" min="1" value={quiz.startingHp} onChange={e=>field('startingHp',+e.target.value)}/></Col><Col md={4}><Form.Label>Skade ved feil</Form.Label><Form.Control type="number" min="1" value={quiz.mistakeDamage} onChange={e=>field('mistakeDamage',+e.target.value)}/></Col><Col md={4} className="d-flex align-items-end"><Form.Check type="switch" label="Publiser quiz" checked={quiz.isPublished} onChange={e=>field('isPublished',e.target.checked)}/></Col></Row></Card.Body></Card>
    <Card className="editor-card mb-3"><Card.Body><div className="d-flex justify-content-between align-items-center"><div><h3>2. Valgfri bosskamp</h3><p>Vanlig quiz fungerer uten boss. Aktiver valget dersom quizen skal avsluttes med en boss.</p></div><Form.Check type="switch" checked={quiz.bossFightEnabled} onChange={e=>field('bossFightEnabled',e.target.checked)}/></div>{quiz.bossFightEnabled&&<Row className="g-3 boss-settings"><Col md={4}><Form.Label>Bossnavn</Form.Label><Form.Control value={quiz.bossName||''} required onChange={e=>field('bossName',e.target.value)}/></Col><Col md={4}><Form.Label>Boss-HP</Form.Label><Form.Control type="number" min="1" value={quiz.bossHp||300} onChange={e=>field('bossHp',+e.target.value)}/></Col><Col md={4}><Form.Label>Skade etter 3 riktige</Form.Label><Form.Control type="number" min="1" value={quiz.bossDamagePerStreak||100} onChange={e=>field('bossDamagePerStreak',+e.target.value)}/></Col></Row>}</Card.Body></Card>
    <div className="d-flex justify-content-between align-items-center mb-3"><h2 className="section-title m-0">3. Spørsmål</h2><Button variant="outline-light" onClick={()=>field('questions',[...quiz.questions,{...emptyQuestion(),order:quiz.questions.length+1}])}>+ Legg til spørsmål</Button></div>
    {quiz.questions.map((question,qi)=><Card className="editor-card question-editor mb-3" key={qi}><Card.Body><div className="d-flex justify-content-between"><h3>Spørsmål {qi+1}</h3>{quiz.questions.length>1&&<Button variant="outline-danger" size="sm" onClick={()=>field('questions',quiz.questions.filter((_,i)=>i!==qi))}>Fjern</Button>}</div><Form.Control className="mb-3" required placeholder="Skriv spørsmålet" value={question.text} onChange={e=>qField(qi,'text',e.target.value)}/><Form.Control className="mb-3" required placeholder="Forklaring som vises etter svar" value={question.explanation} onChange={e=>qField(qi,'explanation',e.target.value)}/><Row className="g-2">{question.answerOptions.map((option,oi)=><Col md={6} key={oi}><div className="answer-row"><Form.Check type="radio" name={`correct-${qi}`} checked={option.isCorrect} onChange={()=>optionField(qi,oi,'isCorrect',true)}/><Form.Control required placeholder={`Svaralternativ ${oi+1}`} value={option.text} onChange={e=>optionField(qi,oi,'text',e.target.value)}/></div></Col>)}</Row></Card.Body></Card>)}
    <div className="d-flex justify-content-end gap-2"><Button variant="outline-light" onClick={()=>go('mine')}>Avbryt</Button><Button type="submit" disabled={saving}>{saving?'Lagrer…':'Lagre quiz'}</Button></div>
  </Form></>
}

